version: "3.9"

services:
  bench:
    build:
      context: .
      dockerfile: Dockerfile
    # remove the line: image: your-image:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - HF_HOME=/workspace/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/workspace/cache/huggingface
      - HF_DATASETS_CACHE=/workspace/cache/huggingface/datasets
    volumes:
      - ./logs:/workspace/logs
      - ./results:/workspace/results
      - ./cache/huggingface:/workspace/cache/huggingface
    shm_size: "8g"
    tty: true
    stdin_open: true
    working_dir: /workspace
